### ISSUE TITLE
[Bug] Crashes using lastest meteor version

### ISSUE THREAD

**Issue by Deponjo** [AntiCope/reaper-addon#11]
### Describe the bug

Crashes when starting minecraft using meteor version 0.5.1 1615

### Crashlog

RuntimeException: Mixin transformation of meteordevelopment.meteorclient.systems.modules.player.FakePlayer failed
<html>at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:419)<br>at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.tryLoadClass(KnotClassDelegate.java:323)<br>at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.loadClass(KnotClassDelegate.java:218)<br>at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:145)<br>at java.lang.ClassLoader.loadClass(ClassLoader.java:521)<br>at net.minecraft.util.crash.CrashReport.handler$cbh000$onAddStackTrace(CrashReport:1524)<br>at net.minecraft.util.crash.CrashReport.addStackTrace(CrashReport:80)<br>at net.minecraft.util.crash.CrashReport.asString(CrashReport:134)<br>at net.minecraft.util.crash.CrashReport.initCrashReport(CrashReport:274)<br>at net.minecraft.client.main.Main.method_44604(Main:159)<br>at net.minecraft.client.main.Main.main(Main:51)<br>at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:461)<br>at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)<br>at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)<br>at jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)<br>at java.lang.reflect.Method.invoke(Method.java:577)<br>at org.polymc.impl.OneSixLauncher.invokeMain(OneSixLauncher.java:104)<br>at org.polymc.impl.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:175)<br>at org.polymc.impl.OneSixLauncher.launch(OneSixLauncher.java:185)<br>at org.polymc.EntryPoint.listen(EntryPoint.java:144)<br>at org.polymc.EntryPoint.main(EntryPoint.java:74)</html>
MixinTransformerError: An unexpected critical error was encountered
<html>at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:392)<br>at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClass(MixinTransformer.java:234)<br>at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClassBytes(MixinTransformer.java:202)<br>at io.gitlab.jfronny.libjf.unsafe.asm.AsmTransformer.transformClassBytes(AsmTransformer.java:77)<br>at meteordevelopment.meteorclient.asm.Asm$Transformer.transformClassBytes(Asm.java:102)<br>at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:414)<br>... 20 more</html>
<html>MixinApplyError: Mixin [reaper.mixins.json:meteor.FakePlayerMixin from mod reaper] from phase [DEFAULT] in config<br>[reaper.mixins.json] FAILED during APPLY</html>
<html>at org.spongepowered.asm.mixin.transformer.MixinProcessor.handleMixinError(MixinProcessor.java:638)<br>at org.spongepowered.asm.mixin.transformer.MixinProcessor.handleMixinApplyError(MixinProcessor.java:589)<br>at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:379)<br>... 25 more</html>
<html>InvalidInjectionException: Critical injection failure: @Inject annotation on onActivate could not find any targets<br>matching 'onActivate' in meteordevelopment.meteorclient.systems.modules.player.FakePlayer. Using refmap<br>reaper-refmap.json [PREINJECT Applicator Phase -&gt; reaper.mixins.json:meteor.FakePlayerMixin from mod reaper -&gt; Prepare<br>Injections -&gt;  -&gt; handler$chp001$onActivate(Lorg/spongepowered/asm/mixin/injection/callback/CallbackInfo;)V -&gt; Parse]</html>
<html>at Not Enough Crashes deobfuscated stack trace.(1.19+build.4)<br>at org.spongepowered.asm.mixin.injection.struct.InjectionInfo.validateTargets(InjectionInfo.java:656)<br>at org.spongepowered.asm.mixin.injection.struct.InjectionInfo.findTargets(InjectionInfo.java:587)<br>at org.spongepowered.asm.mixin.injection.struct.InjectionInfo.readAnnotation(InjectionInfo.java:330)<br>at org.spongepowered.asm.mixin.injection.struct.InjectionInfo.&lt;init&gt;(InjectionInfo.java:316)<br>at org.spongepowered.asm.mixin.injection.struct.InjectionInfo.&lt;init&gt;(InjectionInfo.java:308)<br>at org.spongepowered.asm.mixin.injection.struct.CallbackInjectionInfo.&lt;init&gt;(CallbackInjectionInfo.java:46)<br>at jdk.internal.reflect.DirectConstructorHandleAccessor.newInstance(DirectConstructorHandleAccessor.java:67)<br>at java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:499)<br>at java.lang.reflect.Constructor.newInstance(Constructor.java:483)<br>at org.spongepowered.asm.mixin.injection.struct.InjectionInfo$InjectorEntry.create(InjectionInfo.java:149)<br>at org.spongepowered.asm.mixin.injection.struct.InjectionInfo.parse(InjectionInfo.java:708)<br>at org.spongepowered.asm.mixin.transformer.MixinTargetContext.prepareInjections(MixinTargetContext.java:1330)<br>at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.prepareInjections(MixinApplicatorStandard.java:1043)<br>at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.applyMixin(MixinApplicatorStandard.java:393)<br>at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.apply(MixinApplicatorStandard.java:325)<br>at org.spongepowered.asm.mixin.transformer.TargetClassContext.apply(TargetClassContext.java:421)<br>at org.spongepowered.asm.mixin.transformer.TargetClassContext.applyMixins(TargetClassContext.java:403)<br>at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:363)<br>... 25 more</html>

### Steps to reproduce

1.Install meteor client 0.5.1 1615
2.Start Minecraft
3.Crashes
...

### Operating System

Windows

### Meteor Version

0.5.1-dev 1615

### Minecraft Version

1.19.2

### Other mods

```plaintext
1.
2.
3.
...
```

**Comment by I-Got-You-Dead** [comment]
This is caused by the Reaper addon

**Comment by I-Got-You-Dead** [comment]
It’s mixin is fucked on the latest version of meteor
